# Asynchronous Crypto HFT Trading Configuration

# Data configuration
data:
  symbols: ['ETH_EUR', 'XBT_EUR']  # Crypto pairs to analyze
  raw_data_path: 'data/raw'        # Path to raw order book data

# Order book feature configuration
features:
  depth_levels: 5                  # Number of order book levels to process

# Lead-lag detection parameters
lead_lag:
  max_lag_ms: 1000                # Maximum lag time to consider (1 second)
  min_price_change: 0.0001        # Minimum relative price change (0.01%)
  signal_decay_ms: 5000           # Signal decay time (5 seconds)

# Transaction cost modeling
costs:
  maker_fee: 0.0001               # 0.01% maker fee
  taker_fee: 0.0002               # 0.02% taker fee  
  slippage_bps: 0.5               # 0.5 basis points slippage
  min_commission: 0.01            # Minimum commission per trade

# Trading strategy parameters
strategy:
  initial_capital: 100000         # Starting capital in USD
  position_size: 0.1              # Position size as fraction of capital (10%)
  max_positions: 2                # Maximum concurrent positions
  signal_threshold: 0.5           # Minimum signal confidence to trade (50%)

# Backtest configuration  
backtest:
  in_sample_ratio: 0.7           # 70% for in-sample analysis
  validation_ratio: 0.15         # 15% for parameter optimization
  out_sample_ratio: 0.15         # 15% for final out-of-sample test

# Performance thresholds
performance:
  min_sharpe_ratio: 1.0          # Minimum acceptable Sharpe ratio
  max_drawdown: 0.15             # Maximum acceptable drawdown (15%)
  min_win_rate: 0.45             # Minimum win rate (45%)

# Risk management
risk:
  max_position_value: 20000      # Maximum position value
  stop_loss_pct: 0.02            # Stop loss percentage (2%)
  position_timeout_minutes: 60   # Maximum position holding time

# Output configuration
output:
  results_dir: 'results'         # Directory for results export
  log_level: 'INFO'              # Logging level
  export_trades: true            # Export individual trades
  export_signals: true           # Export lead-lag signals
